version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
  bloomdb:
    container_name: bloomrunnerDb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pwd12345!"
    ports:
      - '1422:1433'
    restart: on-failure

  webgateway.api:
    container_name: webapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Developmentss
    ports:
      - "4001:443"
      - "4000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  authservice.api:
    container_name: authserviceapi
    restart: on-failure
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Data Source=bloomrunnerdb;Initial Catalog=BloomRunner;User id=sa;Password=Pwd12345!;Trusted_Connection=false;Integrated Security=false
    depends_on:
        - bloomdb
    ports:
        - "5001:443"
        - "5000:80"